name: Ontology release
run-name: ${{ github.actor }} is building documentation using GitHub Actions 🚀
on:
  push:
    - main
    - release/*
jobs:
  build_docs:
    name: Build ontology documentation
    runs-on: ubuntu-latest
    steps:
      - run: ./run.sh
