name: Ontology release
run-name: ${{ github.actor }} is building documentation using GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build_docs:
    name: Build ontology documentation
    runs-on: ubuntu-latest
    steps:
      - run: ./.github/run.sh
