name: Ontology release
run-name: ${{ github.actor }} is building documentation using GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./run.sh
  update:
    name: Commit docs
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v9
